[project]
name = "drone-rl"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = [
    "numpy",
    "numpy-quaternion",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "mypy",
    "pytest"
]

[tool.ruff]
line-length = 100
select = ["E", "F", "I", "B"]

[tool.mypy]
python_version = 3.11
check_untyped_defs = true
disallow_untyped_defs = false
ignore_missing_imports = true
exclude = "build|dist|\\.venv|\\.eggs"

[tool.pytest.ini_options]
testpaths = ["tests"]